Application Immobiliere( Extrait)/CodedHomes.Web/ViewModels/HomeViewModel.cs
using CodedHomes.Models;

namespace CodedHomes.Web.ViewModels
{
    public class HomeViewModel : ViewModelBase
    {
        public Home Home { get; set; }
        public bool IsNew { get; set; }

        public string ImageUrlPrefix
        {
            get { return CodedHomes.Web.Config.ImagesUrlPrefix; }
        }

        public HomeViewModel()
        {
            this.Home = new Home();
        }
    }
}

Application Immobiliere( Extrait)/CodedHomes.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodedHomes.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Application Immobiliere( Extrait)/CodedHomes.Web/Controllers/HomesController.cs
using CodedHomes.Data;
using CodedHomes.Models;
using CodedHomes.Web.Filters;
using CodedHomes.Web.ViewModels;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodedHomes.Web.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class HomesController : Controller
    {
        private ApplicationUnit _unit = new ApplicationUnit();

        [AllowAnonymous]
        public ActionResult Index()
        {
            HomesListViewModel vm = new HomesListViewModel();
            var query = this._unit.Homes.GetAll().OrderByDescending(s => s.Price);
            vm.Homes = query.ToList();

            return View("Index", vm);
        }

        [HttpPost()]
        public ActionResult UploadImage(HttpPostedFileBase image, int id)
        {
            JsonResult result;
            Home home;
            Random rand = new Random();
            string unique;
            string ext;
            string fileName;
            string path;

            unique = rand.Next(1000000).ToString();

            ext = Path.GetExtension(image.FileName).ToLower();

            fileName = string.Format("{0}-{1}{2}", id, unique, ext);

            path = Path.Combine(
                HttpContext.Server.MapPath(Config.ImagesFolderPath), fileName);

            if (ext == ".png" || ext == ".jpg")
            {
                home = _unit.Homes.GetById(id);

                if (home != null)
                {
                    home.ImageName = fileName;
                    _unit.Homes.Update(home);
                    _unit.SaveChanges();

                    image.SaveAs(path);
                    result = this.Json(new
                    {
                        imageUrl = string.Format("{0}{1}",
                        Config.ImagesUrlPrefix, fileName)
                    });
                }
                else
                {
                    result = this.Json(new
                    {
                        status = "error",
                        statusText = 
                            string.Format("There is no home with the Id of " + 
                                "'{0}' in the system.", id)
                    });
                }
            }
            else
            {
                result = this.Json(new
                {
                    status = "error",
                    statusText = "Unsupported image type. Only .png or " + 
                        ".jpg files are acceptable."
                });
            }

            return result;
        }

        [ActionName("Edit")]
        public ActionResult Get(int id)
        {
            HomeViewModel vm = new HomeViewModel();

            vm.Home = this._unit.Homes.GetById(id);

            if (vm.Home != null)
            {
                return View("Home", vm);
            }

            return View("NotFound");
        }

        public ActionResult New()
        {
            HomeViewModel vm = new HomeViewModel();
            vm.IsNew = true;

            return View("Home", vm);
        }

        protected override void Dispose(bool disposing)
        {
            this._unit.Dispose();
            base.Dispose(disposing);
        }


        // *********************************** // 
        // ********* Offline Support ********* //
        // *********************************** // 
        [AllowAnonymous]
        public ActionResult Offline()
        {
            return View();
        }

        public ActionResult ReviewOffline()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Manifest()
        {
            this.Response.ContentType = "text/cache-manifest";
            this.Response.Cache.SetCacheability(HttpCacheability.NoCache);

            string viewName = "Manifest";

#if DEBUG
            viewName = "Manifest-Debug";
#endif

            return View(viewName);
        }
    }
}

Application Immobiliere( Extrait)/CodedHomes.Web/Views/Homes/Index.cshtml
@model CodedHomes.Web.ViewModels.HomesListViewModel
@using CodedHomes.Models
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.Title = "Available Homes";
}

@section styles {
	<style>
		.home-row {
			margin-top:20px;
			margin-bottom:20px;
			border-bottom:1px solid #eee;
			padding-bottom:15px;
		}

			.home-row .price {
				font-size:2em;
				color:#666;
			}
	</style>
}

@section scripts {
<script>
	$(function() {

		var ViewModel = function() {

			this.homes = ko.observableArray(@Html.Raw(Model.HomesJSON));


@if (Model.CanDelete)
{
<text>
			this.currentHome = {};

			this.errorMessage = ko.observable();

			this.showError = function(error) {
				$('#error-container').fadeIn();
			};

			this.requestDelConfirm = function(home) {
				vm.currentHome = home;
				$('#del-confirm').modal();
			};

			this.del = function() {
				var home = ko.toJS(vm.currentHome);

				homesDataService.del(home).done(function(response) {
					vm.homes.remove(function(item) {
						return item.id === home.id;
					});
				}).fail(function(error) {
					vm.showError(error);
				}).always(function() {
					$('#del-confirm').modal('hide');
				});
			};
</text>
}
		};

		var vm = new ViewModel();

		_.each(vm.homes(), function(home) {
			home.priceFormatted = ko.computed(function() {
				return _.numberWithCommas(home.price);
			});

			home.imageUrl = ko.computed(function() {
				var
					imgName = home.imageName,
					fileName = (imgName == null) ? 'no-image.png' : imgName,
					url = '@Model.ImageUrlPrefix' + fileName;

				return url;
			});
		});

		ko.applyBindings(vm);
	});
</script>    
}

<h1>Homes</h1>
@if (Model.CanDelete)
{
<div id="error-container" class="none">
	<div class="alert alert-error">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<h4>Oops..</h4>
		<p>Something went wrong. Here's the error message:</p>
		<p data-bind="text: errorMessage"></p>
	</div>
</div>
}
<div id="list-container">
	<div data-bind="template: { name: 'list-template', foreach: homes }"></div>
</div>

<script type="text/html" id="list-template">
	<div class="container-fluid">
		<div class="row-fluid home-row">
			<div class="span2"><img data-bind="attr: {src: imageUrl}" 
				class="fancy" /></div>
			<div class="span10">
				<div class="row-fluid">
					<div class="span3">
						<address>
							<span data-bind="text: streetAddress"></span><br />
							<!-- ko if: $data.streetAddress2 -->
							<span 
								data-bind="text: streetAddress2"></span><br />
							<!-- /ko -->
							<span data-bind="text: city"></span>, CA <span 
								data-bind="text: zipCode"></span>
						</address>
					</div>
					<div class="span3 price" 
						data-bind="text: priceFormatted"></div>
				</div>
				<div class="row-fluid">
					<div class="span6"><p 
						data-bind="text: description"></p></div>
				</div>
				<div class="row-fluid">
@if (Model.CanDelete)
{
						<a href="#" class="btn-mini" 
							data-bind="click: $parent.requestDelConfirm">Delete</a>
}
@if (Model.CanEdit)
{
						<a class="btn btn-primary btn-mini" 
							data-bind="attr: {href: '/homes/edit/' + id}">Edit</a>
}
				</div>
			</div>
		</div>
	</div>
</script>

@if (Model.CanDelete)
{
<div id="del-confirm" class="modal hide fade" tabindex="-1" role="dialog" 
	aria-labelledby="del-confirm-label" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" 
			aria-hidden="true">×</button>
		<h3 id="del-confirm-label">Confirm Delete</h3>
	</div>
	<div class="modal-body">
		<p>Are you sure you want to delete this home?</p>
		<p class="alert alert-error push-down"><strong>Note:</strong> 
			There is no undo for this action.</p>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		<button class="btn btn-primary" data-bind="click: del">Delete Home</button>
	</div>
</div>   
}

Application Immobiliere( Extrait)/CodedHomes.Web/Views/Homes/Manifest-Debug.cshtml
CACHE MANIFEST
# version 1 
# @Url.Content("/views/shared/_Layout.cshtml").AppendHash(Request)
# @Url.Content("/views/home/index.cshtml").AppendHash(Request)
# @Url.Content("/views/homes/Offline.cshtml").AppendHash(Request)

CACHE:
# AppendHash approach from @@ShirtlessKirk via http://bit.ly/12HlyCD
@Url.Content("/content/bootstrap.min.css").AppendHash(Request)
@Url.Content("/content/bootstrap-responsive.css").AppendHash(Request)
@Url.Content("/content/site.css").AppendHash(Request)
@Url.Content("/img/coded-homes-logo.png").AppendHash(Request)
@Url.Content("/img/coded-homes-logo-large.png").AppendHash(Request)
@Url.Content("/scripts/lib/modernizr-2.6.2.js").AppendHash(Request)
@Url.Content("/scripts/lib/jquery-1.9.1.js").AppendHash(Request)
@Url.Content("/scripts/lib/bootstrap.js").AppendHash(Request)
@Url.Content("/scripts/lib/underscore.js").AppendHash(Request)
@Url.Content("/scripts/lib/knockout-2.2.1.debug.js").AppendHash(Request)
@Url.Content("/scripts/lib/H5F.js").AppendHash(Request)
@Url.Content("/scripts/app/homesDataService.js").AppendHash(Request)
@Url.Content("/scripts/app/offlineUtility.js").AppendHash(Request)
@Url.Content("/scripts/app/validationUtility.js").AppendHash(Request)
@Url.Content("/scripts/app/serializer.js").AppendHash(Request)

NETWORK:
*

@{
    Layout = null;
}

@using CodedHomes.Web.Utilities

Application Immobiliere( Extrait)/CodedHomes.Web/Views/Homes/Manifest.cshtml
CACHE MANIFEST
# build 1

CACHE:
/
/homes/offline
/content/bootstrap.min.css
/content/bootstrap-responsive.css
/content/site.css
/img/coded-homes-logo.png
/img/coded-homes-logo-large.png
/scripts/lib/modernizr-2.6.2.js
/scripts/lib/jquery-1.9.1.js
/scripts/lib/bootstrap.js
/scripts/lib/underscore.js
/scripts/lib/knockout-2.2.1.debug.js
/scripts/lib/H5F.js
/scripts/app/homesDataService.js
/scripts/app/offlineUtility.js
/scripts/app/validationUtility.js

NETWORK:
*

@{
    Layout = null;
}

@using CodedHomes.Web.Utilities

Application Immobiliere( Extrait)/CodedHomes.Web/Views/Homes/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<h2>Home Not Found</h2>
<div class="well">
    <p>For some reason the home you're trying to edit isn't available in the system.</p>
    <p>Perhaps you'd like to @Html.ActionLink("view the list of all homes", "Index", "Homes") or
        @Html.ActionLink("add a new home", "new", "Homes")?</p>
</div>

Application Immobiliere( Extrait)/CodedHomes.Web/Views/Homes/Offline.cshtml
@{
    ViewBag.Title = "Offline";
    Layout = "~/Views/Shared/OfflineLayout.cshtml";
}

@section scripts {
    <script>

        $(function() {

            var
                notifyOnlineVersionAvailable = function() {
                    $("#online-alert-container").fadeIn();
                },
                
                hideOnlineLink = function() {
                    $("#online-alert-container").fadeOut('fast');
                };

            var
                offlineUtility = new OfflineUtility(notifyOnlineVersionAvailable, hideOnlineLink),
                homeDataForm = $("#home-data-form")[0];

            var Home = function() {
                this.id = ko.observable();
                this.streetAddress = ko.observable();
                this.streetAddress2 = ko.observable();
                this.city = ko.observable();
                this.zipCode = ko.observable();
                this.bedrooms = ko.observable();
                this.bathrooms = ko.observable();
                this.squareFeet = ko.observable();
                this.price = ko.observable();
                this.description = ko.observable();
            };

            var ViewModel = function(home) {
                this.model = home;

                this.isSupportedByBrowser = ko.observable(Modernizr.localstorage);

                this.isNotSupportedByBrowser = ko.observable(!Modernizr.localstorage);

                this.errorMessage = ko.observable();

                this.showError = function(error) {
                    if (error) {
                        vm.errorMessage(error);
                    }

                    $('#fail-msg-container').fadeIn();
                };

                this.showSuccess = function() {

                    $('#fail-msg-container').fadeOut();
                    $('#success-msg-container').fadeIn();

                    var fadeOut = function() {
                        $('#success-msg-container').fadeOut()
                    };

                    _.delay(fadeOut, 5000);
                };

                this.save = function() {
                    try {

                        var validationUtility = new ValidationUtility();

                        if (validationUtility.validate('home-data-form')) {
                            var
                                home = ko.toJS(this.model),
                                serialized = JSON.stringify(home);

                            debugger;

                            homesDataService.saveLocal(serialized);

                            vm.model.streetAddress('');
                            vm.model.streetAddress2('');
                            vm.model.city('');
                            vm.model.zipCode('');
                            vm.model.bedrooms('');
                            vm.model.bathrooms('');
                            vm.model.squareFeet('');
                            vm.model.price('');
                            vm.model.description('');

                            this.showSuccess();
                        }
                    } catch (e) {
                        this.showError(e.message);
                    }

                };
            };

            var vm = new ViewModel(new Home());

            H5F.setup([homeDataForm], {
                validClass: "valid",
                invalidClass: "invalid",
                requiredClass: "required"
            });

            ko.applyBindings(vm);
        });
    </script>    
}

<h1>Add New Home</h1>
<div class="row-fluid">
    <form id="home-data-form" data-bind="visible: isSupportedByBrowser">
        <div class="span5 mobile-push-right">
            <div class="row-fluid">
                <div class="span11">
                    <input id="streetAddress" name="streetAddress" data-bind="value: model.streetAddress" 
                        type="text" class="full" autofocus
                        data-role="validate"
                        title="Street Address"
                        data-content="The Street Address is required."
                        placeholder="street address" required />
                    <br />

                    <input id="streeAddress2" name="city" data-bind="value: model.streetAddress2" 
                        type="text" class="full" 
                        placeholder="suite, apt. #, etc." /><br />

                    <input id="city" name="city" data-bind="value: model.city" 
                        title="City"
                        data-role="validate"
                        data-content="City is required."
                        type="text" class="small" 
                        placeholder="city" required /> CA 

                    <input id="zipCode" name="zipCode" data-bind="value: model.zipCode" 
                        title="Zip Code"
                        data-role="validate"
                        data-content="Zip Code required."
                        type="number" class="no-spin small push-right" 
                        placeholder="zip code" required />
                </div>
            </div>

            <hr />

            <div class="row-fluid stats">
                <div class="span3"><label for="bedrooms">Price</label></div>
                <div class="span6"><input data-bind="value: model.price" 
                    title="Price"
                    data-role="validate"
                    data-content="Price is required."
                    id="price" name="price"
                    type="number" class="no-spin small" required /></div>
            </div>

            <div class="row-fluid stats">
                <div class="span3"><label for="bedrooms">Bedrooms</label></div>
                <div class="span6"><input data-bind="value: model.bedrooms" 
                    id="bedrooms" name="bedrooms"
                    title="Bedrooms"
                    data-role="validate"
                    data-content="The number of bedrooms is required."
                    type="number" class="no-spin small" required /></div>
            </div>

            <div class="row-fluid stats">
                <div class="span3"><label for="bathrooms">Bathrooms</label></div>
                <div class="span6"><input data-bind="value: model.bathrooms"
                    id="bathrooms" name="bathrooms" 
                    title="Bathrooms"
                    data-role="validate"
                    data-content="The number of bathrooms is required."
                    type="number" class="no-spin small" required /></div>
            </div>

            <div class="row-fluid stats">
                <div class="span3"><label for="square-feet">Square Feet</label></div>
                <div class="span6"><input 
                    id="square-feet" name="square-feet" data-bind="value: model.squareFeet"
                    title="Square Feet"
                    data-role="validate"
                    data-content="The square feet of the home is required."
                    type="number" class="no-spin small" required /></div>
            </div>

            <hr />

            <div class="row-fluid">
                <div class="span11">
                    <label for="description">Description</label>
                    <textarea data-bind="value: model.description" 
                        id="description" name="description"
                        class="full" required
                        title="Description"
                        data-role="validate"
                        data-content="A description is required."></textarea>
                </div>
            </div>

            <hr />

            <div class="row-fluid">
                <div class="span11">
                    <div id="command-buttons" class="pull-right">
                        <button data-bind="click: save" 
                                type="button" 
                                class="btn btn-primary btn-large push-right cmd">Save</button>
                    </div>
                </div>
            </div>

            <!-- Message Containers  -->
            <div class="row-fluid">
                <div id="success-msg-container" class="span11 alert alert-success alert-block push-down">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <h4>Home Saved Offline</h4>
                    <p>You'll have a chance to send homes added while offline 
                        to the server when you regain connection to the web.</p>
                </div>
                <div id="fail-msg-container" class="span11 alert alert-error alert-block push-down">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <h4>Error</h4>
                    <p>Oops, something bad happened! This is what the error message has to say about it:</p>
                    <p data-bind="text: errorMessage"></p>
                </div>
            </div>
            <!-- /Message Containers  -->

        </div>
    </form>
    <div id="unsupported-browser" class="well push-down none" data-bind="visible: isNotSupportedByBrowser">
        <h2>Unsupported Browser</h2>
        <p>
            Unfortunatley your browser doesn't support this application in offline mode.
            Please try again once you are again connected to the internet.
        </p>
    </div>
</div>

@section breakout {
<div id="online-alert-container" class="alert alert-success none sticky-message">
    Your connection is restored! <a href="/homes/new/">Click here to add homes directly into the system.</a>
</div>    
}

Application Immobiliere( Extrait)/CodedHomes.Web/Views/Homes/ReviewOffline.cshtml
@{
    ViewBag.Title = "Review Homes Saved While Offline";
}

@section scripts {
    <script>

        $(function() {

            var ViewModel = function(data) {

                this.homes = ko.observableArray(data);

                this.errorMessage = ko.observable();

                this.showSuccess = function() {
                    $("#failure").fadeOut();
                    $("#success").fadeIn();

                    var fadeOut = function() {
                        $("#success").fadeOut();
                    };

                    _.delay(fadeOut, 5000);
                };

                this.updateLayout = function() {
                    if (_(vm.homes()).size() === 0) {
                        $('#review-homes-container').fadeOut(function() {
                            $('#done-container').fadeIn();
                        });
                    }
                };

                this.showFailure = function() {
                    $("#failure").fadeIn();
                    $("#success").fadeOut();
                };

                this.save = function(home) {
                    debugger;

                    homesDataService.save(home).done(function() {
                        try {
                            vm.del(home);
                            vm.showSuccess();
                            vm.updateLayout();
                        } catch (e) {
                            vm.showFailure(e);
                        }

                    }).fail(function(error) {
                        vm.errorMessage = error;
                        vm.showFailure();
                    });
                };

                this.del = function(home) {
                    debugger;
                    try {
                        homesDataService.delLocal(home);
                        vm.homes.remove(home);
                        vm.updateLayout();
                    }
                    catch (e) {
                        vm.errorMessage = error;
                        vm.showFailure();
                    }
                };
            };

            var
                key = homesDataService.localKey,
                data = window.localStorage.getItem(key),
                homes = [];

            if (data != undefined && data != 'undefined') {
                homes = homesDataService.parse(data);
            } else {
                homes = [];
            }

            var vm = new ViewModel(homes);
            ko.applyBindings(vm);

            vm.updateLayout();


        });

    </script>    
}

<div id="review-homes-container">
    <h2>Review Homes Added Offline</h2>
    <div class="container-fluid">
        <div class="span6">
            <div data-bind="template: { name: 'home-template', foreach: homes }"></div>
        </div>
        <div class="span4">
            <div id="success" class="alert alert-success none">
                <h4>Home Saved</h4>
                <p>The home is now saved on the server.</p>
            </div>
            <div id="failure" class="alert alert-error none">
                <h4>Oops!</h4>
                <p>Something went wrong. The error message is: <span data-bind="text: errorMessage"></span>.</p>
            </div>
        </div>
    </div>
</div>

<div id="done-container" class="none well">
    <h2>Done!</h2>
    <p>You processed all the homes that were saved while offline.</p>
</div>


<script type="text/html" id="home-template">
    <div>
        <address>
            <span data-bind="text: streetAddress"></span><br />
            <!-- ko if: $data.streetAddress2 --><span data-bind="text: streetAddress2"></span><br /><!-- /ko -->
            <span data-bind="text: city"></span>, CA <span data-bind="text: zipCode"></span>
        </address>
        <p data-bind="text: description"></p>
        <button class="btn btn-mini" data-bind="click: $parent.del">Delete</button>
        <button class="btn btn-mini btn-primary" data-bind="click: $parent.save">Save</button>
        <hr />
    </div>
</script>